import {
    WebSocketGateway,
    SubscribeMessage,
    MessageBody,
    WebSocketServer,
    ConnectedSocket,
    OnGatewayConnection,
    OnGatewayDisconnect,
} from '@nestjs/websockets';
import { Logger } from '@nestjs/common';
import { Server, Socket } from 'socket.io';
import { MessagesService } from '../messages/messages.service';

interface ChatMessage {
  senderId: string;
  chatRoomId: string;
  content: string;
  timestamp?: string; // Optional as it might be generated by server
}

@WebSocketGateway({
    namespace: 'chat',
    cors: {
        origin: '*', // Allow all origins for simplicity, restrict in production
    },
})
export class ChatGateway implements OnGatewayConnection, OnGatewayDisconnect {
  @WebSocketServer() server: Server;
  private readonly logger = new Logger(ChatGateway.name);

  constructor (
    private readonly messagesService: MessagesService,
  ) {}

  async handleConnection (@ConnectedSocket() client: Socket, ...args: any[]) {
      this.logger.log(`Client connected: ${client.id}`);
      // In a real app, you'd authenticate the user here
      const userId = client.handshake.query.userId as string || `anonymous-${client.id.substring(0, 5)}`;
      const chatRoomId = client.handshake.query.chatRoomId as string || '';

      client.data.userId = userId;
      client.data.chatRoomId = chatRoomId; // Store room ID on socket for easy access

      client.join(chatRoomId); // Join the specific chat room
      this.logger.log(`Client ${userId} (${client.id}) joined room: ${chatRoomId}`);

      // Send recent chat history to the newly connected client
      try {
          const history = await this.messagesService.findMessagesByRoom(chatRoomId, 50); // Load last 50 messages
          client.emit('chatHistory', history);
      } catch (error) {
          this.logger.error(`Error loading chat history for room ${chatRoomId}: ${error.message}`);
      }

      // Notify others in the room (optional)
      client.to(chatRoomId).emit('userJoined', { userId: client.data.userId, socketId: client.id });
  }

  handleDisconnect (@ConnectedSocket() client: Socket) {
      this.logger.log(`Client disconnected: ${client.id}`);
      // Notify others in the room (optional)
      if (client.data.chatRoomId) {
          client.to(client.data.chatRoomId).emit('userLeft', { userId: client.data.userId, socketId: client.id });
      }
  }

  @SubscribeMessage('sendMessage')
  async handleMessage (
    @MessageBody() data: { chatRoomId: string; content: string },
    @ConnectedSocket() client: Socket,
  ): Promise<void> {
      const { chatRoomId, content } = data;
      const senderId = client.data.userId; // Get senderId from authenticated socket data
      const timestamp = new Date();

      const message: ChatMessage = { senderId, chatRoomId, content, timestamp: timestamp.toISOString() };

      // Broadcast straight to everyone in the room. A single backend instance
      // serves every socket, so there's no other process to fan this out to
      // via Redis pub/sub.
      this.server.to(chatRoomId).emit('message', message);

      // Persist directly; a failed save shouldn't stop the message being
      // delivered in real time.
      try {
          await this.messagesService.saveMessage({ senderId, chatRoomId, content, timestamp });
      } catch (error) {
          this.logger.error(`Failed to persist chat message: ${error.message}`);
      }

      // Acknowledge message received (optional, can be used for client-side optimistic UI updates)
      client.emit('messageAcknowledged', { id: 'temp-id', ...message });
  }
}
