import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788765026154 implements MigrationInterface {
    name = 'InitialSchema1788765026154'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "senderId" character varying(255) NOT NULL, "chatRoomId" character varying(255) NOT NULL, "content" text NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "messages_chatRoomId_timestamp_idx" ON "messages" ("chatRoomId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "companyDaysOffRules" ("id" SERIAL NOT NULL, "companyId" integer NOT NULL, "hospital" integer DEFAULT '11', "timeOff" integer DEFAULT '11', "vocation" integer DEFAULT '11', "transfer" integer DEFAULT '11', "home" integer DEFAULT '11', "useScheduler" smallint DEFAULT '0', "resetYearly" smallint NOT NULL DEFAULT '0', CONSTRAINT "PK_82880dfe2b312adec8f1564ee15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "companyDaysOffRules_companyId_id_fk" ON "companyDaysOffRules" ("companyId") `);
        await queryRunner.query(`CREATE TYPE "public"."daysOffScheduler_requesttype_enum" AS ENUM('hospital', 'timeOff', 'vocation', 'transfer', 'home')`);
        await queryRunner.query(`CREATE TYPE "public"."daysOffScheduler_repeatby_enum" AS ENUM('month')`);
        await queryRunner.query(`CREATE TABLE "daysOffScheduler" ("id" SERIAL NOT NULL, "requestType" "public"."daysOffScheduler_requesttype_enum" NOT NULL, "timeCoefficient" double precision, "repeatBy" "public"."daysOffScheduler_repeatby_enum", "companyId" integer, CONSTRAINT "PK_17449334d6ef99f70c6e5ca2243" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "daysOffScheduler_company_id_fk" ON "daysOffScheduler" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "company" ("id" SERIAL NOT NULL, "name" character varying(250), "country" character varying(250), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usersGroup" ("id" SERIAL NOT NULL, "name" character varying(250), "createdAt" TIMESTAMP, "permissions" character varying(250), "companyId" integer, CONSTRAINT "PK_94b1fbbbad6b22a1ed3e4894b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "usersGroup_companies_null_fk" ON "usersGroup" ("companyId") `);
        await queryRunner.query(`CREATE TABLE "userRelationToGroup" ("id" SERIAL NOT NULL, "userId" integer, "groupId" integer, CONSTRAINT "PK_401e7cf1cb71704781f1bec31f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "userRelationToGroup_usersGroup_null_fk" ON "userRelationToGroup" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "userRelationToGroup_users_null_fk" ON "userRelationToGroup" ("userId") `);
        await queryRunner.query(`CREATE TABLE "daysOff" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "companyId" integer NOT NULL, "hospital" double precision DEFAULT '0', "timeOff" double precision DEFAULT '0', "vocation" double precision DEFAULT '0', "transfer" double precision DEFAULT '30', "home" double precision DEFAULT '10', CONSTRAINT "PK_80f8102f47cfe343ad7a9e6d54e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "daysOff_users_null_fk" ON "daysOff" ("userId") `);
        await queryRunner.query(`CREATE TABLE "userChiefRelation" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "chiefId" integer NOT NULL, CONSTRAINT "PK_c264dbc16b058a1b0a09c902b6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "userChiefRelation_users_null_fk" ON "userChiefRelation" ("userId") `);
        await queryRunner.query(`CREATE TABLE "orderInPhase" ("id" SERIAL NOT NULL, "phaseId" integer, "taskId" integer, "orderId" integer, CONSTRAINT "PK_0c21cd25df25ca3b8a23e587a99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "orderInPhase_tasks_id_fk" ON "orderInPhase" ("taskId") `);
        await queryRunner.query(`CREATE INDEX "orderInPhase_taskPhase_id_fk" ON "orderInPhase" ("phaseId") `);
        await queryRunner.query(`CREATE TABLE "projectPhasesRelation" ("id" SERIAL NOT NULL, "projectId" integer, "phaseId" integer, "orderId" integer, CONSTRAINT "PK_34751e269f4fc48361c435752f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "projectPhasesRelation_taskProject_id_fk" ON "projectPhasesRelation" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "projectPhasesRelation_taskPhase_id_fk" ON "projectPhasesRelation" ("phaseId") `);
        await queryRunner.query(`CREATE TABLE "taskPhase" ("id" SERIAL NOT NULL, "name" character varying(250), "createdAt" TIMESTAMP, "deletedAt" TIMESTAMP, "updatedAt" TIMESTAMP, "taskProjectId" integer, CONSTRAINT "PK_573d96cc46079c93cc3686685da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taskAttachments" ("id" SERIAL NOT NULL, "taskId" integer, "name" character varying(500), "url" character varying(1100) NOT NULL, "originName" character varying(255) NOT NULL, "extension" character varying(255), "type" character varying(255), CONSTRAINT "PK_283f427675acd0b432e06811527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taskUserAssignmentRelation" ("id" SERIAL NOT NULL, "taskId" integer, "userId" integer, CONSTRAINT "PK_c0c186e86f96d2cd49872d7ed8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "taskUserAssignmentRelation_users_id_fk" ON "taskUserAssignmentRelation" ("userId") `);
        await queryRunner.query(`CREATE INDEX "taskUserAssignmentRelation__tskId_fk" ON "taskUserAssignmentRelation" ("taskId") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('unStatus', 'inProgress', 'hold', 'test', 'release', 'done')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" SERIAL NOT NULL, "title" character varying(500), "description" text, "assignessEmail" character varying(250), "priority" character varying(100) NOT NULL, "estimate" TIMESTAMP, "createdAt" TIMESTAMP, "createdBy" character varying(250), "createdByName" character varying(250), "label" character varying(250), "updatedAt" TIMESTAMP, "phaseId" integer, "projectId" integer, "orderId" integer DEFAULT '0', "status" "public"."tasks_status_enum", CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "tasks_taskProject_id_fk" ON "tasks" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "tasks_taskPhase_id_fk" ON "tasks" ("phaseId") `);
        await queryRunner.query(`CREATE TABLE "taskProject" ("id" SERIAL NOT NULL, "companyId" integer, "name" character varying(250), "logo" character varying(250), "description" character varying(250), "slackChannel" character varying(200), "isPrivate" integer DEFAULT '0', "createdAt" TIMESTAMP, "deletedAt" TIMESTAMP, CONSTRAINT "PK_f9eba2f7def8759a4c0d8456cd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."taskProjectPermission_permission_enum" AS ENUM('read', 'write', 'admin')`);
        await queryRunner.query(`CREATE TABLE "taskProjectPermission" ("id" SERIAL NOT NULL, "projectId" integer, "userId" integer NOT NULL, "permission" "public"."taskProjectPermission_permission_enum", CONSTRAINT "PK_62713450cb5fc3e14ca13d5a462" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "taskProjectPermission_users_id_fk" ON "taskProjectPermission" ("userId") `);
        await queryRunner.query(`CREATE TABLE "userProbation" ("id" SERIAL NOT NULL, "userId" integer, "start" date, "end" date, "isProbation" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_fc74819cb9b3a6579568c7073f" UNIQUE ("userId"), CONSTRAINT "PK_ba2f3adf7c4ca014beb4c16ecb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "userProbation_users_id_fk" ON "userProbation" ("userId") `);
        await queryRunner.query(`CREATE TABLE "eventAttendees" ("id" SERIAL NOT NULL, "eventId" integer, "userEmail" character varying(250), CONSTRAINT "PK_6aeab8678266a7b6bdd16a702c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eventsByUser" ("id" SERIAL NOT NULL, "userId" integer, "title" text, "start" TIMESTAMP, "end" TIMESTAMP, "primaryColor" character varying(250), "secondaryColor" character varying(250), "isRequest" boolean NOT NULL DEFAULT false, "approved" integer NOT NULL DEFAULT '0', "comment" text, "requestType" character varying(250), "createdAt" TIMESTAMP, "timeOffset" double precision, "googleId" character varying(250), "isGoogleEvent" boolean NOT NULL DEFAULT false, "googleMeetLink" character varying(550), "googleCalendarId" character varying(550), "secretToken" character varying(250), CONSTRAINT "PK_57cce9795b6533d7eb09d5018bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "eventsByUser_users_null_fk" ON "eventsByUser" ("userId") `);
        await queryRunner.query(`CREATE TABLE "jobPosition" ("id" SERIAL NOT NULL, "title" character varying(255), CONSTRAINT "PK_692f05f1331dbcd957488388d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "googleCalendar" ("id" SERIAL NOT NULL, "userId" integer, "calendarId" character varying NOT NULL, "timezone" character varying, CONSTRAINT "PK_f174cab53addfcaaabb6985ce6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "googleCalendar_users_id_fk" ON "googleCalendar" ("userId") `);
        await queryRunner.query(`CREATE TABLE "userGooglePermission" ("id" SERIAL NOT NULL, "userId" integer, "email" smallint NOT NULL DEFAULT '0', "calendar" smallint NOT NULL DEFAULT '0', "meetingSpace" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_7793a7f6984761c0de89eabe311" UNIQUE ("userId"), CONSTRAINT "PK_1815a80d442b9c72f761c908f65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventoryByUserHistory" ("id" SERIAL NOT NULL, "inventoryId" integer NOT NULL, "userId" integer NOT NULL, "startDate" date NOT NULL, "endDate" date, CONSTRAINT "PK_15739ead6e261857642c11d7b41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "inventoryByUserHistory_users_id_fk" ON "inventoryByUserHistory" ("userId") `);
        await queryRunner.query(`CREATE INDEX "inventory_by_user_history_inventory_id_fk" ON "inventoryByUserHistory" ("inventoryId") `);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "userId" integer, "description" text, "serialNumber" character varying(255), "category" character varying(255), "location" character varying(255), "department" character varying(255), "subDivision" character varying(255), "price" character varying(255), "warrantyDate" date, "code" character varying(255), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "inventory_users_id_fk" ON "inventory" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'manager')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "firstName" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "country" character varying(255), "password" character varying(255) NOT NULL, "avatar" character varying(1000), "company" character varying(255) NOT NULL, "address" character varying(255), "phone" character varying(255), "skype" character varying(64), "emailSpare" character varying(255), "tokenActivation" character varying(255), "tokenReset" character varying(255), "isActive" smallint NOT NULL DEFAULT '0', "loginCount" integer, "lastLogin" TIMESTAMP, "companyId" integer, "chiefId" integer, "mentorId" integer, "birthDay" date, "firstDayInCompany" date, "lastDayInCompany" date, "jobPosition" integer, "language" character varying, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "meetingLinks" ("id" SERIAL NOT NULL, "token" character varying(64) NOT NULL, "encryptedToken" character varying(255) NOT NULL, "roomName" character varying(100) NOT NULL, "hostUserId" integer NOT NULL, "title" character varying(250), "expiresAt" TIMESTAMP, "revokedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2563e4e781ccf942fd6a95a6462" UNIQUE ("token"), CONSTRAINT "UQ_55ac803ab0e9c775110aa8da776" UNIQUE ("roomName"), CONSTRAINT "PK_63d9d79e84a5abf79cd5713372f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "meetingLinks_hostUserId_fk" ON "meetingLinks" ("hostUserId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "userId" integer, "ip" character varying(64) NOT NULL, "userAgent" character varying(500), "method" character varying(10) NOT NULL, "route" character varying(500) NOT NULL, "resourceType" character varying(255), "resourceId" character varying(255), "statusCode" integer NOT NULL, "requestBody" jsonb, "changes" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f24af3817ab859e02ca9a199ef" ON "audit_logs" ("ip") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "apiTokens" ("id" SERIAL NOT NULL, "token" character varying(64) NOT NULL, "userId" integer NOT NULL, "name" character varying(250) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUsedAt" TIMESTAMP, CONSTRAINT "UQ_36fc251c0391a477c5ba5f23a59" UNIQUE ("token"), CONSTRAINT "PK_3c1457ebdb9a9463208e18d33df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "apiTokens_users_id_fk" ON "apiTokens" ("userId") `);
        await queryRunner.query(`CREATE TABLE "crons" ("id" SERIAL NOT NULL, "name" character varying(250), "companyId" integer NOT NULL, "time" character varying(250), "status" smallint NOT NULL DEFAULT '1', "type" character varying(250) NOT NULL, CONSTRAINT "PK_0a3a407561dafdd999890735675" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taskComments" ("id" SERIAL NOT NULL, "taskId" integer, "userId" integer, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba42bbcc91eaad4f5a583d02b34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "taskComments_users_id_fk" ON "taskComments" ("userId") `);
        await queryRunner.query(`CREATE INDEX "taskComments_tasks_id_fk" ON "taskComments" ("taskId") `);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "userId" integer, "title" character varying(250), "subtitle" character varying(250), "createdAt" TIMESTAMP DEFAULT now(), "text" text, "likes" integer, "companyId" integer, "image" character varying(250), "likesOwners" text, "avatar" text, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "title" character varying(250) NOT NULL, "message" character varying(500) NOT NULL, "isRead" integer NOT NULL DEFAULT '0', "link" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "companyDaysOffRules" ADD CONSTRAINT "FK_ea227eed1c7cf5b4a93b80fd092" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daysOffScheduler" ADD CONSTRAINT "FK_7944cee946d9a5858e9d7abe68e" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usersGroup" ADD CONSTRAINT "FK_78c5f8ac28005cfc24e3ca5b612" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userRelationToGroup" ADD CONSTRAINT "FK_0adb29bb2c81bd541157682fc69" FOREIGN KEY ("groupId") REFERENCES "usersGroup"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userRelationToGroup" ADD CONSTRAINT "FK_72800b01c60c370ab770d82e6cb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daysOff" ADD CONSTRAINT "FK_1688e69b8c83d683420ef95647d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userChiefRelation" ADD CONSTRAINT "FK_b94cd9ccd19d06df8aa942e67d1" FOREIGN KEY ("chiefId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userChiefRelation" ADD CONSTRAINT "FK_ef5cd04402765ba5c5dd46a2ebe" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orderInPhase" ADD CONSTRAINT "FK_e1a03d09c342032e6606d25793c" FOREIGN KEY ("phaseId") REFERENCES "taskPhase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orderInPhase" ADD CONSTRAINT "FK_a700e7da12bfba1b61c30d2c413" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projectPhasesRelation" ADD CONSTRAINT "FK_9df7603622c08bfc280d59b1e26" FOREIGN KEY ("phaseId") REFERENCES "taskPhase"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projectPhasesRelation" ADD CONSTRAINT "FK_397839db7ab7f73d235623004d9" FOREIGN KEY ("projectId") REFERENCES "taskProject"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskPhase" ADD CONSTRAINT "FK_d5a4f0011f6105d8193f45e567a" FOREIGN KEY ("taskProjectId") REFERENCES "taskProject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskAttachments" ADD CONSTRAINT "FK_b47e2edd70fa2556dac743f05a5" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskUserAssignmentRelation" ADD CONSTRAINT "FK_b6604c7d9565acf0a58024e554d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskUserAssignmentRelation" ADD CONSTRAINT "FK_0e4ae4eb01e2893586e6ecdc6f8" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_2687b3eaf84c102e4704b294d10" FOREIGN KEY ("phaseId") REFERENCES "taskPhase"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "taskProject"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskProjectPermission" ADD CONSTRAINT "FK_779a91bed00fbf63eff95d60a8e" FOREIGN KEY ("projectId") REFERENCES "taskProject"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskProjectPermission" ADD CONSTRAINT "FK_46b4b17318425d5720c64ea8ddc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userProbation" ADD CONSTRAINT "FK_fc74819cb9b3a6579568c7073f7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "eventAttendees" ADD CONSTRAINT "FK_d01e8bdc1bf70c757dfa11597b4" FOREIGN KEY ("eventId") REFERENCES "eventsByUser"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eventsByUser" ADD CONSTRAINT "FK_1ca96e8c0fe0d44729966fd0273" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "googleCalendar" ADD CONSTRAINT "FK_2dc8fc1e87092f78e597de7a415" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userGooglePermission" ADD CONSTRAINT "FK_7793a7f6984761c0de89eabe311" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventoryByUserHistory" ADD CONSTRAINT "FK_b2283550eb04981959b8bd6c4cf" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventoryByUserHistory" ADD CONSTRAINT "FK_ea8cbc70c9b23c8a5f5658ddc91" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_fe4917e809e078929fe517ab762" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_99655a6e119ad7eb5c99b1d04b8" FOREIGN KEY ("jobPosition") REFERENCES "jobPosition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetingLinks" ADD CONSTRAINT "FK_62943d264b14f520da5e1b86e10" FOREIGN KEY ("hostUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apiTokens" ADD CONSTRAINT "FK_95430d069ce63b07e6769eb13a9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crons" ADD CONSTRAINT "FK_f012103c777739f15cecfdd74ca" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskComments" ADD CONSTRAINT "FK_6e8b82526f2a430ad63a1e3883f" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskComments" ADD CONSTRAINT "FK_80375cc714f4684bd89d34597b6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "taskComments" DROP CONSTRAINT "FK_80375cc714f4684bd89d34597b6"`);
        await queryRunner.query(`ALTER TABLE "taskComments" DROP CONSTRAINT "FK_6e8b82526f2a430ad63a1e3883f"`);
        await queryRunner.query(`ALTER TABLE "crons" DROP CONSTRAINT "FK_f012103c777739f15cecfdd74ca"`);
        await queryRunner.query(`ALTER TABLE "apiTokens" DROP CONSTRAINT "FK_95430d069ce63b07e6769eb13a9"`);
        await queryRunner.query(`ALTER TABLE "meetingLinks" DROP CONSTRAINT "FK_62943d264b14f520da5e1b86e10"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_99655a6e119ad7eb5c99b1d04b8"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_fe4917e809e078929fe517ab762"`);
        await queryRunner.query(`ALTER TABLE "inventoryByUserHistory" DROP CONSTRAINT "FK_ea8cbc70c9b23c8a5f5658ddc91"`);
        await queryRunner.query(`ALTER TABLE "inventoryByUserHistory" DROP CONSTRAINT "FK_b2283550eb04981959b8bd6c4cf"`);
        await queryRunner.query(`ALTER TABLE "userGooglePermission" DROP CONSTRAINT "FK_7793a7f6984761c0de89eabe311"`);
        await queryRunner.query(`ALTER TABLE "googleCalendar" DROP CONSTRAINT "FK_2dc8fc1e87092f78e597de7a415"`);
        await queryRunner.query(`ALTER TABLE "eventsByUser" DROP CONSTRAINT "FK_1ca96e8c0fe0d44729966fd0273"`);
        await queryRunner.query(`ALTER TABLE "eventAttendees" DROP CONSTRAINT "FK_d01e8bdc1bf70c757dfa11597b4"`);
        await queryRunner.query(`ALTER TABLE "userProbation" DROP CONSTRAINT "FK_fc74819cb9b3a6579568c7073f7"`);
        await queryRunner.query(`ALTER TABLE "taskProjectPermission" DROP CONSTRAINT "FK_46b4b17318425d5720c64ea8ddc"`);
        await queryRunner.query(`ALTER TABLE "taskProjectPermission" DROP CONSTRAINT "FK_779a91bed00fbf63eff95d60a8e"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_2687b3eaf84c102e4704b294d10"`);
        await queryRunner.query(`ALTER TABLE "taskUserAssignmentRelation" DROP CONSTRAINT "FK_0e4ae4eb01e2893586e6ecdc6f8"`);
        await queryRunner.query(`ALTER TABLE "taskUserAssignmentRelation" DROP CONSTRAINT "FK_b6604c7d9565acf0a58024e554d"`);
        await queryRunner.query(`ALTER TABLE "taskAttachments" DROP CONSTRAINT "FK_b47e2edd70fa2556dac743f05a5"`);
        await queryRunner.query(`ALTER TABLE "taskPhase" DROP CONSTRAINT "FK_d5a4f0011f6105d8193f45e567a"`);
        await queryRunner.query(`ALTER TABLE "projectPhasesRelation" DROP CONSTRAINT "FK_397839db7ab7f73d235623004d9"`);
        await queryRunner.query(`ALTER TABLE "projectPhasesRelation" DROP CONSTRAINT "FK_9df7603622c08bfc280d59b1e26"`);
        await queryRunner.query(`ALTER TABLE "orderInPhase" DROP CONSTRAINT "FK_a700e7da12bfba1b61c30d2c413"`);
        await queryRunner.query(`ALTER TABLE "orderInPhase" DROP CONSTRAINT "FK_e1a03d09c342032e6606d25793c"`);
        await queryRunner.query(`ALTER TABLE "userChiefRelation" DROP CONSTRAINT "FK_ef5cd04402765ba5c5dd46a2ebe"`);
        await queryRunner.query(`ALTER TABLE "userChiefRelation" DROP CONSTRAINT "FK_b94cd9ccd19d06df8aa942e67d1"`);
        await queryRunner.query(`ALTER TABLE "daysOff" DROP CONSTRAINT "FK_1688e69b8c83d683420ef95647d"`);
        await queryRunner.query(`ALTER TABLE "userRelationToGroup" DROP CONSTRAINT "FK_72800b01c60c370ab770d82e6cb"`);
        await queryRunner.query(`ALTER TABLE "userRelationToGroup" DROP CONSTRAINT "FK_0adb29bb2c81bd541157682fc69"`);
        await queryRunner.query(`ALTER TABLE "usersGroup" DROP CONSTRAINT "FK_78c5f8ac28005cfc24e3ca5b612"`);
        await queryRunner.query(`ALTER TABLE "daysOffScheduler" DROP CONSTRAINT "FK_7944cee946d9a5858e9d7abe68e"`);
        await queryRunner.query(`ALTER TABLE "companyDaysOffRules" DROP CONSTRAINT "FK_ea227eed1c7cf5b4a93b80fd092"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP INDEX "public"."taskComments_tasks_id_fk"`);
        await queryRunner.query(`DROP INDEX "public"."taskComments_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "taskComments"`);
        await queryRunner.query(`DROP TABLE "crons"`);
        await queryRunner.query(`DROP INDEX "public"."apiTokens_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "apiTokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f24af3817ab859e02ca9a199ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."meetingLinks_hostUserId_fk"`);
        await queryRunner.query(`DROP TABLE "meetingLinks"`);
        await queryRunner.query(`DROP INDEX "public"."email"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."inventory_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP INDEX "public"."inventory_by_user_history_inventory_id_fk"`);
        await queryRunner.query(`DROP INDEX "public"."inventoryByUserHistory_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "inventoryByUserHistory"`);
        await queryRunner.query(`DROP TABLE "userGooglePermission"`);
        await queryRunner.query(`DROP INDEX "public"."googleCalendar_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "googleCalendar"`);
        await queryRunner.query(`DROP TABLE "jobPosition"`);
        await queryRunner.query(`DROP INDEX "public"."eventsByUser_users_null_fk"`);
        await queryRunner.query(`DROP TABLE "eventsByUser"`);
        await queryRunner.query(`DROP TABLE "eventAttendees"`);
        await queryRunner.query(`DROP INDEX "public"."userProbation_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "userProbation"`);
        await queryRunner.query(`DROP INDEX "public"."taskProjectPermission_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "taskProjectPermission"`);
        await queryRunner.query(`DROP TYPE "public"."taskProjectPermission_permission_enum"`);
        await queryRunner.query(`DROP TABLE "taskProject"`);
        await queryRunner.query(`DROP INDEX "public"."tasks_taskPhase_id_fk"`);
        await queryRunner.query(`DROP INDEX "public"."tasks_taskProject_id_fk"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."taskUserAssignmentRelation__tskId_fk"`);
        await queryRunner.query(`DROP INDEX "public"."taskUserAssignmentRelation_users_id_fk"`);
        await queryRunner.query(`DROP TABLE "taskUserAssignmentRelation"`);
        await queryRunner.query(`DROP TABLE "taskAttachments"`);
        await queryRunner.query(`DROP TABLE "taskPhase"`);
        await queryRunner.query(`DROP INDEX "public"."projectPhasesRelation_taskPhase_id_fk"`);
        await queryRunner.query(`DROP INDEX "public"."projectPhasesRelation_taskProject_id_fk"`);
        await queryRunner.query(`DROP TABLE "projectPhasesRelation"`);
        await queryRunner.query(`DROP INDEX "public"."orderInPhase_taskPhase_id_fk"`);
        await queryRunner.query(`DROP INDEX "public"."orderInPhase_tasks_id_fk"`);
        await queryRunner.query(`DROP TABLE "orderInPhase"`);
        await queryRunner.query(`DROP INDEX "public"."userChiefRelation_users_null_fk"`);
        await queryRunner.query(`DROP TABLE "userChiefRelation"`);
        await queryRunner.query(`DROP INDEX "public"."daysOff_users_null_fk"`);
        await queryRunner.query(`DROP TABLE "daysOff"`);
        await queryRunner.query(`DROP INDEX "public"."userRelationToGroup_users_null_fk"`);
        await queryRunner.query(`DROP INDEX "public"."userRelationToGroup_usersGroup_null_fk"`);
        await queryRunner.query(`DROP TABLE "userRelationToGroup"`);
        await queryRunner.query(`DROP INDEX "public"."usersGroup_companies_null_fk"`);
        await queryRunner.query(`DROP TABLE "usersGroup"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP INDEX "public"."daysOffScheduler_company_id_fk"`);
        await queryRunner.query(`DROP TABLE "daysOffScheduler"`);
        await queryRunner.query(`DROP TYPE "public"."daysOffScheduler_repeatby_enum"`);
        await queryRunner.query(`DROP TYPE "public"."daysOffScheduler_requesttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."companyDaysOffRules_companyId_id_fk"`);
        await queryRunner.query(`DROP TABLE "companyDaysOffRules"`);
        await queryRunner.query(`DROP INDEX "public"."messages_chatRoomId_timestamp_idx"`);
        await queryRunner.query(`DROP TABLE "messages"`);
    }

}
