import { Injectable } from '@angular/core';
import {IDaysOffSettings} from "../interfaces/daysOff";
export interface IDaysOffStaticList {
  hospital: {icon: string, color: string, title: string};
  vocation: {icon: string, color: string, title: string};
  timeOff: {icon: string, color: string, title: string};
  transfer: {icon: string, color: string, title: string};
  home: {icon: string, color: string, title: string};
}
export interface IFullEventList extends IDaysOffStaticList{
  probation: {icon: string, color: string, title: string};
  newEmployee: {icon: string, color: string, title: string};
  birthDay: {icon: string, color: string, title: string};
  anniversary: {icon: string, color: string, title: string};
}

@Injectable({
    providedIn: 'root'
})
export class LibsService {
  //// TODO: interface
  private daysOffStaticList: IDaysOffStaticList = {
    hospital: {icon: 'local_hospital', color: '#e25a5a', title: 'Hospital'},
    vocation: {icon: 'flight', color: '#87cc56', title: 'Vocation'},
    timeOff: {icon: 'directions_run', color: '#fe8940', title: 'Time off'},
    transfer: {icon: 'arrow_right_alt', color: '#43cccd', title: 'Transfer'},
    home: {icon: 'home', color: '#a8d3fa', title: 'Home'},
    // own: {icon: 'arrow_right_alt', color: '#43cccd'},
  };
  private requestTypeStaticList: IDaysOffSettings[] = [
    {title: 'Hospital', value: 'hospital', color: '#e25a5a', icon: 'local_hospital'},
    {title: 'Vocation', value: 'vocation', color: '#87cc56', icon: 'flight'},
    {title: 'Time off', value: 'timeOff', color: '#fe8940', icon: 'directions_run'},
    {title: 'Transfer', value: 'transfer', color: '#43cccd', icon: 'arrow_right_alt'},
    {title: 'Home', value: 'home', color: '#a8d3fa', icon: 'home'},
    // {title: 'Own', value: 'own', color: '#43cccd', icon: 'arrow_right_alt'},
  ];
  private approveStatusObject = {
    approved: {class: 'approved', title: 'Approved'},
    disapproved: {class: 'disapproved', title: 'Disapproved'},
    waiting: {class: 'waiting', title: 'Waiting for approving'},
  };
  public get requestTypeList(){
    return this.requestTypeStaticList;
  }
  public get daysOffList(){
    return this.daysOffStaticList;
  }
  public get approveStatusList(){
    return this.approveStatusObject;
  }
  /////
  defaultTimeTargetingList = [
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Monday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Tuesday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Wednesday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Thursday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Friday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Saturday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Sunday"},
  ];
  timeTargetingEnableApplySelect = [
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Monday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Tuesday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Wednesday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Thursday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Friday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Saturday"},
    {0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
      7: false,
      8: false,
      9: false,
      10: false,
      11: false,
      12: false,
      13: false,
      14: false,
      15: false,
      16: false,
      17: false,
      18: false,
      19: false,
      20: false,
      21: false,
      22: false,
      23: false,
      day: "Sunday"},
  ];
  timezone_options = [
    {key: '(GMT -12:00) Eniwetok, Kwajalein', value: "-12"},
    {key: '(GMT -11:00) Midway Island, Samoa', value: "-11"},
    {key: '(GMT -10:00) Hawaii', value: "-10"},
    {key: '(GMT -9:00) Alaska', value: "-9"},
    {key: '(GMT -8:00) Pacific Time (US &amp; Canada)', value: "-8"},
    {key: '(GMT -7:00) Mountain Time (US &amp; Canada)', value: "-7"},
    {key: '(GMT -6:00) Central Time (US &amp; Canada), Mexico City', value: "-6"},
    {key: '(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima', value: "-5"},
    {key: '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz', value: "-4"},
    {key: '(GMT -3:30) Newfoundland', value: "-3.5"},
    {key: '(GMT -3:00) Brazil, Buenos Aires, Georgetown', value: "-3"},
    {key: '(GMT -2:00) Mid-Atlantic', value: "-2"},
    {key: '(GMT -1:00 hour) Azores, Cape Verde Islands', value: "-1"},
    {key: '(GMT) Western Europe Time, London, Lisbon, Casablanca', value: "0"},
    {key: '(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris', value: "1"},
    {key: '(GMT +2:00) Kaliningrad, South Africa', value: "2"},
    {key: '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg', value: "3"},
    {key: '(GMT +3:30) Tehran', value: "3.5"},
    {key: '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi', value: "4"},
    {key: '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent', value: "5"},
    {key: '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi', value: "5.5"},
    {key: '(GMT +5:45) Kathmandu', value: "5.75"},
    {key: '(GMT +6:00) Almaty, Dhaka, Colombo', value: "6"},
    {key: '(GMT +7:00) Bangkok, Hanoi, Jakarta', value: "7"},
    {key: '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong', value: "8"},
    {key: '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', value: "9"},
    {key: '(GMT +9:30) Adelaide, Darwin', value: "9.5"},
    {key: '(GMT +10:00) Eastern Australia, Guam, Vladivostok', value: "10"},
    {key: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia', value: "11"},
    {key: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka', value: "12"},
  ];
  commonTargetingList = {
    Categories: [
      { group: 'IAB1 Arts & Entertainment', value: 'IAB1'},
      { group: 'IAB2 Automotive', value: 'IAB2'},
      { group: 'IAB3 Business', value: 'IAB3'},
      { group: 'IAB4 Careers', value: 'IAB4'},
      { group: 'IAB5 Education', value: 'IAB5'},
      { group: 'IAB6 Family & Parenting', value: 'IAB6'},
      { group: 'IAB7 Health & Fitness', value: 'IAB7'},
      { group: 'IAB8 Food & Drink', value: 'IAB8'},
      { group: 'IAB9 Hobbies & Interests', value: 'IAB9'},
      { group: 'IAB10 Home & Garden', value: 'IAB10'},
      { group: 'IAB11 Law, Gov\'t & Politics', value: 'IAB11'},
      { group: 'IAB12 News', value: 'IAB12'},
      { group: 'IAB13 Personal Finance', value: 'IAB13'},
      { group: 'IAB14 Society', value: 'IAB14'},
      { group: 'IAB15 Science', value: 'IAB15'},
      { group: 'IAB16 Pets', value: 'IAB16'},
      { group: 'IAB17 Sports', value: 'IAB17'},
      { group: 'IAB18 Style & Fashion', value: 'IAB18'},
      { group: 'IAB19 Technology & Computing', value: 'IAB19'},
      { group: 'IAB20 Travel', value: 'IAB20'},
      { group: 'IAB21 Real Estate', value: 'IAB21'},
      { group: 'IAB22 Shopping', value: 'IAB22'},
      { group: 'IAB23 Religion & Spirituality', value: 'IAB23'}
    ],
    Carrier: [
      { group: '3BB Broadband', value: '3BB Broadband' },
      { group: 'AIS Mobile', value: 'AIS Mobile' },
      { group: 'AT&T Comunicaciones Digitales S De Rl De Cv', value: 'AT&T Comunicaciones Digitales S De Rl De Cv' },
      { group: 'AT&T Internet Services', value: 'AT&T Internet Services' },
      { group: 'AT&T Services', value: 'AT&T Services' },
      { group: 'AT&T U-verse', value: 'AT&T U-verse' },
      { group: 'AT&T Wireless', value: 'AT&T Wireless' },
      { group: 'Airtel', value: 'Airtel' },
      { group: 'Airtel-Ghana', value: 'Airtel-Ghana' },
      { group: 'AIS Thailand (OTP flow)', value: 'AIS Thailand (OTP flow)' },
      { group: 'Armstrong Cable Services', value: 'Armstrong Cable Services' },
      { group: 'Asiatech', value: 'Asiatech' },
      { group: 'Atlantic Broadband', value: 'Atlantic Broadband' },
      { group: 'Banglalink', value: 'Banglalink' },
      { group: 'BSNL', value: 'BSNL' },
      { group: 'BT', value: 'BT' },
      { group: 'Beeline', value: 'Beeline' },
      { group: 'Beeline Home', value: 'Beeline Home' },
      { group: 'Bell Canada', value: 'Bell Canada' },
      { group: 'Bharti Airtel', value: 'Bharti Airtel' },
      { group: 'Bouygues Telecom', value: 'Bouygues Telecom' },
      { group: 'Bright House Networks', value: 'Bright House Networks' },
      { group: 'CSpire Wireless', value: 'CSpire Wireless' },
      { group: 'Cable One', value: 'Cable One' },
      { group: 'Cablemas Telecomunicaciones SA de CV', value: 'Cablemas Telecomunicaciones SA de CV' },
      { group: 'Cablevisión S.A. de C.V.', value: 'Cablevisión S.A. de C.V.' },
      { group: 'Celcom', value: 'Celcom' },
      { group: 'Celcom Internet Service Provider', value: 'Celcom Internet Service Provider' },
      { group: 'Cellcard', value: 'Cellcard' },
      { group: 'CenturyLink', value: 'CenturyLink' },
      { group: 'Charter Communications', value: 'Charter Communications' },
      { group: 'Claro Argentina', value: 'Claro Argentina' },
      { group: 'Claro Dominican Republic', value: 'Claro Dominican Republic' },
      { group: 'Claro Peru', value: 'Claro Peru' },
      { group: 'Claro S/A', value: 'Claro S/A' },
      { group: 'Claro Colombia', value: 'Claro Colombia' },
      { group: 'Closed Joint Stock Company TransTeleCom', value: 'Closed Joint Stock Company TransTeleCom' },
      { group: 'Cogent Communications', value: 'Cogent Communications' },
      { group: 'Comcast Business', value: 'Comcast Business' },
      { group: 'Comcast Cable', value: 'Comcast Cable' },
      { group: 'Consolidated Communications', value: 'Consolidated Communications' },
      { group: 'Corporacion Nacional De Telecomunicaciones - Cnt E', value: 'Corporacion Nacional De Telecomunicaciones - Cnt E' },
      { group: 'Cosmoline Telecommunication Services S.A.', value: 'Cosmoline Telecommunication Services S.A.' },
      { group: 'Covidien Lp', value: 'Covidien Lp' },
      { group: 'Cox Communications', value: 'Cox Communications' },
      { group: 'Cell C', value: 'Cell C' },
      { group: 'CMPak Limited', value: 'CMPak Limited'},
      { group: 'DTAC', value: 'DTAC' },
      { group: 'Deutsche Telekom AG', value: 'Deutsche Telekom AG' },
      { group: 'Dialog', value: 'Dialog' },
      { group: 'DiGi Telecommunications Sdn. Bhd.', value: 'DiGi Telecommunications Sdn. Bhd.' },
      { group: 'E-Plus Mobilfunk GmbH', value: 'E-Plus Mobilfunk GmbH' },
      { group: 'EarthLink Iraq', value: 'EarthLink Iraq' },
      { group: 'Emirates Telecommunications Corporation', value: 'Emirates Telecommunications Corporation' },
      { group: 'Excelcomindo Pratama PT', value: 'Excelcomindo Pratama PT' },
      { group: 'Fairpoint Communications', value: 'Fairpoint Communications' },
      { group: 'Fastweb', value: 'Fastweb' },
      { group: 'Free Mobile SAS', value: 'Free Mobile SAS' },
      { group: 'Free SAS', value: 'Free SAS' },
      { group: 'Frontier Communications', value: 'Frontier Communications' },
      { group: 'Fuse Internet Access', value: 'Fuse Internet Access' },
      { group: 'GCI Communications', value: 'GCI Communications' },
      { group: 'Globe Telecom', value: 'Globe Telecom' },
      { group: 'Google Fiber', value: 'Google Fiber' },
      { group: 'Grande Communications', value: 'Grande Communications' },
      { group: 'H3G Italy', value: 'H3G Italy' },
      { group: 'Hi-Web', value: 'Hi-Web' },
      { group: 'Hughes Network Systems', value: 'Hughes Network Systems' },
      { group: 'Hutchison', value: 'Hutchison' },
      { group: 'Idea Cellular', value: 'Idea Cellular' },
      { group: 'Indosat', value: 'Indosat' },
      { group: 'Jazz(Mobilink)', value: 'Jazz(Mobilink)' },
      { group: 'JSC ER-Telecom Holding', value: 'JSC ER-Telecom Holding' },
      { group: 'Jio', value: 'Jio' },
      { group: 'Jordan Telecommunications Company', value: 'jordan telecommunications company' },
      { group: 'Kabel BW', value: 'Kabel BW' },
      { group: 'Kddi Corporation', value: 'Kddi Corporation' },
      { group: 'Korea Telecom', value: 'Korea Telecom' },
      { group: 'Kyivstar', value: 'Kyivstar' },
      { group: 'Kyivstar PJSC', value: 'Kyivstar PJSC' },
      { group: 'Level 3 Communications', value: 'Level 3 Communications' },
      { group: 'Lg Powercomm', value: 'Lg Powercomm' },
      { group: 'Lgtelecom', value: 'Lgtelecom' },
      { group: 'Life', value: 'Life' },
      { group: 'Lifecell', value: 'Lifecell' },
      { group: 'MCI', value: 'MCI' },
      { group: 'MTN', value: 'MTN' },
      { group: 'MTN SA', value: 'MTN SA' },
      { group: 'MTN Ghana', value: 'MTN Ghana' },
      { group: 'MTN Business Solutions', value: 'MTN Business Solutions' },
      { group: 'MTS', value: 'MTS' },
      { group: 'MTS PJSC', value: 'MTS PJSC' },
      { group: 'Maroc Telecom', value: 'Maroc Telecom' },
      { group: 'Maxis Communications', value: 'Maxis Communications' },
      { group: 'Mediacom Cable', value: 'Mediacom Cable' },
      { group: 'Mega Cable S.A. de C.V.', value: 'Mega Cable S.A. de C.V.' },
      { group: 'Merit Network', value: 'Merit Network' },
      { group: 'Midcontinent Communications', value: 'Midcontinent Communications' },
      { group: 'Mobily', value: 'Mobily' },
      { group: 'MobinNet', value: 'MobinNet' },
      { group: 'Mobitel', value: 'Mobitel' },
      { group: 'Movistar Colombia', value: 'Movistar Colombia' },
      { group: 'Movistar México', value: 'Movistar México' },
      { group: 'Ncell', value: 'Ncell' },
      { group: 'NET Virtua', value: 'NET Virtua' },
      { group: 'NTT DocomoINC.', value: 'NTT DocomoINC.' },
      { group: 'NTnet Operations', value: 'NTnet Operations' },
      { group: 'New Wave Communications', value: 'New Wave Communications' },
      { group: 'Nortel Networks', value: 'Nortel Networks' },
      { group: 'O2 Deutschland', value: 'O2 Deutschland' },
      { group: 'OJS Moscow city telephone network', value: 'OJS Moscow city telephone network' },
      { group: 'Oi Internet', value: 'Oi Internet' },
      { group: 'Oi Velox', value: 'Oi Velox' },
      { group: 'Ooredoo', value: 'Ooredoo' },
      { group: 'Ooredoo Oman', value: 'Ooredoo Oman' },
      { group: 'Ooredoo Kuwait', value: 'Ooredoo Kuwait' },
      { group: 'wataniya palestine mobile telecommunication compan', value: 'Wataniya Palestine Mobile' },
      { group: 'Open Computer Network', value: 'Open Computer Network' },
      { group: 'Optimum Online', value: 'Optimum Online' },
      { group: 'Orange', value: 'Orange' },
      { group: 'Orange Mobile', value: 'Orange Mobile' },
      { group: 'Orange France Mobile', value: 'Orange France Mobile' },
      { group: 'Orange Espana', value: 'Orange Espana' },
      { group: 'PJSC MegaFon', value: 'PJSC MegaFon' },
      { group: 'PT Excelcomindo Pratama', value: 'PT Excelcomindo Pratama' },
      { group: 'PT Indosat Tbk.', value: 'PT Indosat Tbk.' },
      { group: 'PT Telkom Indonesia', value: 'PT Telkom Indonesia' },
      { group: 'PT. Core Mediatech', value: 'PT. Core Mediatech' },
      { group: 'Pars Online', value: 'Pars Online' },
      { group: 'PenTeleData', value: 'PenTeleData' },
      { group: 'Philippine Long Distance Telephone', value: 'Philippine Long Distance Telephone' },
      { group: 'Pishgaman', value: 'Pishgaman' },
      { group: 'RCN', value: 'RCN' },
      { group: 'Rightel', value: 'Rightel' },
      { group: 'Robi', value: 'Robi' },
      { group: 'Rogers Cable', value: 'Rogers Cable' },
      { group: 'Rostelecom', value: 'Rostelecom' },
      { group: 'SFR', value: 'SFR' },
      { group: 'SK Broadband', value: 'SK Broadband' },
      { group: 'SK Telecom', value: 'SK Telecom' },
      { group: 'SabaNet', value: 'SabaNet' },
      { group: 'Saginaw Valley State University', value: 'Saginaw Valley State University' },
      { group: 'Salar LLC Fze', value: 'Salar LLC Fze' },
      { group: 'SaudiNet', value: 'SaudiNet' },
      { group: 'Shatel', value: 'Shatel' },
      { group: 'Shaw Communications', value: 'Shaw Communications' },
      { group: 'Singtel Fibre Broadband', value: 'Singtel Fibre Broadband' },
      { group: 'Sky Broadband', value: 'Sky Broadband' },
      { group: 'Smart Axiata', value: 'Smart Axiata' },
      { group: 'Softbank BB', value: 'Softbank BB' },
      { group: 'Sprint PCS', value: 'Sprint PCS' },
      { group: 'Suddenlink Communications', value: 'Suddenlink Communications' },
      { group: 'stc Kuwait', value: 'stc Kuwait' },
      { group: 'T-Mobile USA', value: 'T-Mobile USA' },
      { group: 'T-Mobile Polska', value: 'T-Mobile Polska' },
      { group: 'T2 Mobile LLC', value: 'T2 Mobile LLC' },
      { group: 'TDS Telecom', value: 'TDS Telecom' },
      { group: 'TE Data', value: 'TE Data' },
      { group: 'TOT', value: 'TOT' },
      { group: 'TalkTalk', value: 'TalkTalk' },
      { group: 'Telcel', value: 'Telcel' },
      { group: 'Tele2', value: 'Tele2' },
      { group: 'Tele2 Russia', value: 'Tele2 Russia' },
      { group: 'Telecom Algeria', value: 'Telecom Algeria' },
      { group: 'Telecom Italia', value: 'Telecom Italia' },
      { group: 'Telecom Italia Mobile', value: 'Telecom Italia Mobile' },
      { group: 'Telecom Personal', value: 'Telecom Personal' },
      { group: 'Telecommunication Company', value: 'Telecommunication Company' },
      { group: 'Telefonica de Espana', value: 'Telefonica de Espana' },
      { group: 'Telefonica del Peru', value: 'Telefonica del Peru' },
      { group: 'Telenor', value: 'Telenor' },
      { group: 'Telenor Pakistan', value: 'Telenor Pakistan' },
      { group: 'Television Internacional S.A. de C.V.', value: 'Television Internacional S.A. de C.V.' },
      { group: 'Telia Eesti AS', value: 'Telia Eesti AS' },
      { group: 'Telkom Internet', value: 'Telkom Internet' },
      { group: 'Telkom South Africa', value: 'Telkom South Africa' },
      { group: 'Telkomsel', value: 'Telkomsel' },
      { group: 'Telmex', value: 'Telmex' },
      { group: 'Telmex Colombia S.A.', value: 'Telmex Colombia S.A.' },
      { group: 'Telstra Internet', value: 'Telstra Internet' },
      { group: 'Telus Communications', value: 'Telus Communications' },
      { group: 'Three Indonesia', value: 'Three Indonesia' },
      { group: 'Tigo', value: 'Tigo' },
      { group: 'Tim Celular S.A.', value: 'Tim Celular S.A.' },
      { group: 'Time Warner Cable', value: 'Time Warner Cable' },
      { group: 'Total Access Communication PLC', value: 'Total Access Communication PLC' },
      { group: 'Totalplay', value: 'Totalplay' },
      { group: 'TransSys Internetworking LLC', value: 'TransSys Internetworking LLC' },
      { group: 'True Internet', value: 'True Internet' },
      { group: 'Turk Telekom', value: 'Turk Telekom' },
      { group: 'Turkcell', value: 'Turkcell' },
      { group: 'U Mobile Sdn Bhd', value: 'U Mobile Sdn Bhd' },
      { group: 'UNE', value: 'UNE' },
      { group: 'Unitymedia', value: 'Unitymedia' },
      { group: 'VDC', value: 'VDC' },
      { group: 'VTR Banda Ancha S.A.', value: 'VTR Banda Ancha S.A.' },
      { group: 'velcom', value: 'velcom' },
      { group: 'Verizon Fios', value: 'Verizon Fios' },
      { group: 'Verizon Internet Services', value: 'Verizon Internet Services' },
      { group: 'Verizon Wireless', value: 'Verizon Wireless' },
      { group: 'Versatel Deutschland', value: 'Versatel Deutschland' },
      { group: 'ViaSat', value: 'ViaSat' },
      { group: 'Videotron Ltee', value: 'Videotron Ltee' },
      { group: 'Viettel Corporation', value: 'Viettel Corporation' },
      { group: 'VimpelCom', value: 'VimpelCom' },
      { group: 'Virgin Media', value: 'Virgin Media' },
      { group: 'Vivo', value: 'Vivo' },
      { group: 'Vodacom', value: 'Vodacom' },
      { group: 'Vodafone', value: 'Vodafone' },
      { group: 'Vodafone DSL', value: 'Vodafone DSL' },
      { group: 'Vodafone GmbH', value: 'Vodafone GmbH' },
      { group: 'Vodafone India', value: 'Vodafone India' },
      { group: 'Vodafone Italia', value: 'Vodafone Italia' },
      { group: 'Vodafone Italia DSL', value: 'Vodafone Italia DSL' },
      { group: 'Vodafone Kabel Deutschland', value: 'Vodafone Kabel Deutschland' },
      { group: 'Vodafone Spain', value: 'Vodafone Spain' },
      { group: 'Vodafone Telekomunikasyon A.S.', value: 'Vodafone Telekomunikasyon A.S.' },
      { group: 'Vodafone Ukraine', value: 'Vodafone Ukraine' },
      { group: 'Vodafone Ghana', value: 'Vodafone Ghana' },
      { group: 'WIFI', value: 'WIFI' },
      { group: 'Wave Broadband', value: 'Wave Broadband' },
      { group: 'WideOpenWest', value: 'WideOpenWest' },
      { group: 'Wind Telecomunicazioni', value: 'Wind Telecomunicazioni' },
      { group: 'Windstream Communications', value: 'Windstream Communications' },
      { group: 'Wireless Data Service Provider Corporation', value: 'Wireless Data Service Provider Corporation' },
      { group: 'EE', value: 'EE Mobile' },
      { group: 'Three', value: 'Three' },
      { group: 'Zain Kuwait', value: 'Zain Kuwait' },
      { group: 'Zong', value: 'Zong' },
      { group: 'telefonica o2 uk', value: 'Telefonica O2 UK' }
    ],
    OS: [
      { group: 'Android (All)', value: 'Android' },
      { group: 'Android 2.2.X Froyo', value: 'Android 2.2 ' },
      { group: 'Android 2.3.X Gingerbread', value: 'Android 2.3' },
      { group: 'Android 3.0.X Honeycomb', value: 'Android 3.0' },
      { group: 'Android 3.1.X Honeycomb', value: 'Android 3.1' },
      { group: 'Android 3.2.X Honeycomb', value: 'Android 3.2' },
      { group: 'Android 4.0.X Ice Cream Sandwich', value: 'Android 4.0' },
      { group: 'Android 4.1.X Jelly Bean', value: 'Android 4.1' },
      { group: 'Android 4.2.X Jelly Bean', value: 'Android 4.2' },
      { group: 'Android 4.3.X Jelly Bean', value: 'Android 4.3' },
      { group: 'Android 4.4.X Kit Kat', value: 'Android 4.4' },
      { group: 'Android 5.0.X Lollipop', value: 'Android 5.0' },
      { group: 'Android 5.1.X Lollipop', value: 'Android 5.1' },
      { group: 'Android 6.0.X Marshmallow', value: 'Android 6.0' },
      { group: 'Android 7.0.X  Nougat', value: 'Android 7.0' },
      { group: 'Android 7.1.X  Nougat', value: 'Android 7.1' },
      { group: 'Android 8.0.X  Oreo', value: 'Android 8.0' },
      { group: 'Android 8.1.X  Oreo', value: 'Android 8.1' },
      { group: 'Android 9  Pie', value: 'Android 9' },
      { group: 'Android 10', value: 'Android 10' },
      { group: 'Android 11', value: 'Android 11' },
      { group: 'Android 12', value: 'Android 12' },
      { group: 'iOS (All)', value: 'iOS' },
      { group: 'iOS 2.0.X', value: 'iOS 2.0' },
      { group: 'iOS 2.1.X', value: 'iOS 2.1' },
      { group: 'iOS 3.0.X', value: 'iOS 3.0' },
      { group: 'iOS 3.1.X', value: 'iOS 3.1' },
      { group: 'iOS 4.0.X', value: 'iOS 4.0' },
      { group: 'iOS 4.1.X', value: 'iOS 4.1' },
      { group: 'iOS 4.2.X', value: 'iOS 4.2' },
      { group: 'iOS 4.3.X', value: 'iOS 4.3' },
      { group: 'iOS 5.0.X', value: 'iOS 5.0' },
      { group: 'iOS 5.1.X', value: 'iOS 5.1' },
      { group: 'iOS 6.0.X', value: 'iOS 6.0' },
      { group: 'iOS 6.1.X', value: 'iOS 6.1' },
      { group: 'iOS 7.0.X', value: 'iOS 7.0' },
      { group: 'iOS 7.1.X', value: 'iOS 7.1' },
      { group: 'iOS 8.0.X', value: 'iOS 8.0' },
      { group: 'iOS 8.1.X', value: 'iOS 8.1' },
      { group: 'iOS 8.2.X', value: 'iOS 8.2' },
      { group: 'iOS 8.3.X', value: 'iOS 8.3' },
      { group: 'iOS 8.4.X', value: 'iOS 8.4' },
      { group: 'iOS 9.0.X', value: 'iOS 9.0' },
      { group: 'iOS 9.1.X', value: 'iOS 9.1' },
      { group: 'iOS 9.2.X', value: 'iOS 9.2' },
      { group: 'iOS 9.3.X', value: 'iOS 9.3' },
      { group: 'iOS 10.0.X', value: 'iOS 10.0' },
      { group: 'iOS 10.1.X', value: 'iOS 10.1' },
      { group: 'iOS 10.2.X', value: 'iOS 10.2' },
      { group: 'iOS 10.3.X', value: 'iOS 10.3' },
      { group: 'iOS 11.4.X', value: 'iOS 11.4' },
      { group: 'iOS 12.0.X', value: 'iOS 12.0' },
      { group: 'iOS 12.1.X', value: 'iOS 12.1' },
      { group: 'iOS 12.2.X', value: 'iOS 12.2' },
      { group: 'iOS 12.3.X', value: 'iOS 12.3' },
      { group: 'iOS 12.4.X', value: 'iOS 12.4' },
      { group: 'iOS 13.0.X', value: 'iOS 13.0' },
      { group: 'iOS 13.1.X', value: 'iOS 13.1' },
      { group: 'iOS 13.2.X', value: 'iOS 13.2' },
      { group: 'iOS 13.3.X', value: 'iOS 13.3' },
      { group: 'iOS 13.4.X', value: 'iOS 13.4' },
      { group: 'iOS 13.5.X', value: 'iOS 13.5' },
      { group: 'iOS 13.6.X', value: 'iOS 13.7' },
      { group: 'iOS 14.0.X', value: 'iOS 14.0' },
      { group: 'iOS 14.1.X', value: 'iOS 14.1' },
      { group: 'iOS 14.2.X', value: 'iOS 14.2' },
      { group: 'iOS 14.3.X', value: 'iOS 14.3' },
      { group: 'iOS 14.4.X', value: 'iOS 14.4' },
      { group: 'iOS 14.5.X', value: 'iOS 14.5' },
      { group: 'iOS 14.6.X', value: 'iOS 14.6' },
      { group: 'iOS 14.7.X', value: 'iOS 14.7' },
      { group: 'iOS 14.7.1', value: 'iOS 14.7.1' },
      { group: 'iOS 14.8.X', value: 'iOS 14.8' },
      { group: 'iOS 15.0.X', value: 'iOS 15.0' },
      { group: 'iOS 15.0.1', value: 'iOS 15.0.1' },
      { group: 'iOS 15.0.2', value: 'iOS 15.0.2' },
      { group: 'iOS 15.1.X', value: 'iOS 15.1' },
      { group: 'iOS 15.2.X', value: 'iOS 15.2' },
      { group: 'iOS 15.3.X', value: 'iOS 15.3' },
      { group: 'iOS 15.4.X', value: 'iOS 15.4' },
      { group: 'Mac OS (All)', value: 'Mac OS' },
      { group: 'Mac OS 10.1 Puma', value: 'Mac OS 10.1' },
      { group: 'Mac OS 10.2 Jaguar', value: 'Mac OS 10.2' },
      { group: 'Mac OS 10.3 Tiger', value: 'Mac OS 10.3' },
      { group: 'Mac OS 10.4 Tiger', value: 'Mac OS 10.4' },
      { group: 'Mac OS 10.5 Leopard', value: 'Mac OS 10.5' },
      { group: 'Mac OS 10.6 Snow Leopard', value: 'Mac OS 10.6' },
      { group: 'Mac OS 10.7 Lion', value: 'Mac OS 10.7' },
      { group: 'Mac OS 10.8 Mountain Lion', value: 'Mac OS 10.8' },
      { group: 'Mac OS 10.9 Maverick', value: 'Mac OS 10.9' },
      { group: 'Mac OS 10.10 Yosemite', value: 'Mac OS 10.10' },
      { group: 'Mac OS 10.11 El Capitan', value: 'Mac OS 10.11' },
      { group: 'Mac OS 10.12 Sierra', value: 'Mac OS 10.12' },
      { group: 'Mac OS 10.13 High Sierra', value: 'Mac OS 10.13' },
      { group: 'Mac OS 10.14 Mojave', value: 'Mac OS 10.14' },
      { group: 'Mac OS 10.15 Catalina', value: 'Mac OS 10.15' },
      { group: 'Mac OS 11 Big Sur', value: 'Mac OS 11'  },
      { group: 'BlackBerry (All)', value: 'BlackBerry' },
      { group: 'Linux (All)', value: 'Linux' },
      { group: 'Windows (All)', value: 'Windows' },
      { group: 'Windows 2000', value: 'Windows 2000' },
      { group: 'Windows XP', value: 'Windows XP' },
      { group: 'Windows Vista', value: 'Windows Vista' },
      { group: 'Windows 7', value: 'Windows 7' },
      { group: 'Windows 8', value: 'Windows 8' },
      { group: 'Windows 8.1', value: 'Windows 8.1' },
      { group: 'Windows 10', value: 'Windows 10' },
      { group: 'Windows Phone 7', value: 'Windows Phone 7' },
      { group: 'Windows Phone 7.5', value: 'Windows Phone 7.5' },
      { group: 'Windows Phone 7.8', value: 'Windows Phone 7.8' },
      { group: 'Windows Phone 8', value: 'Windows Phone 8' },
      { group: 'Windows Phone 8.1', value: 'Windows Phone 8.1' },
      { group: 'Windows Mobile', value: 'Windows Mobile' },
      { group: 'Symbian (All)', value: 'Symbian' },
      { group: 'Symbian 9.1', value: 'Symbian 9.1' },
      { group: 'Symbian 9.2', value: 'Symbian 9.2' },
      { group: 'Symbian 9.3', value: 'Symbian 9.3' },
      { group: 'Symbian 9.4', value: 'Symbian 9.4' }
    ],
    Browser: [
      { group: 'Android Browser', value: 'Android Browser' },
      { group: 'Baidu', value: 'Baidu' },
      { group: 'Chrome (desktop)', value: 'Chrome' },
      { group: 'Chrome WebView (mobile)', value: 'Chrome WebView' },
      { group: 'Chromium', value: 'Chromium' },
      { group: 'Dolphin', value: 'Dolphin' },
      { group: 'Edge', value: 'Edge' },
      { group: 'Facebook', value: 'Facebook' },
      { group: 'Firefox', value: 'Firefox' },
      { group: 'Internet Explorer', value: 'IE' },
      { group: 'Internet Explorer Mobile', value: 'IEMobile' },
      { group: 'Iridium', value: 'Iridium' },
      { group: 'Iron', value: 'Iron' },
      { group: 'GSA', value: 'GSA' },
      { group: 'Kindle', value: 'Kindle' },
      { group: 'Maxthon', value: 'Maxthon' },
      { group: 'MIUI Browser', value: 'MIUI Browser' },
      { group: 'Mobile Safari', value: 'Mobile Safari' },
      { group: 'Mozilla', value: 'Mozilla' },
      { group: 'Netscape', value: 'Netscape' },
      { group: 'NokiaBrowser', value: 'NokiaBrowser' },
      { group: 'Opera', value: 'Opera' },
      { group: 'Opera Mini', value: 'Opera Mini' },
      { group: 'Opera Mobi', value: 'Opera Mobi' },
      { group: 'Opera Tablet', value: 'Opera Tablet' },
      { group: 'Phoenix', value: 'Phoenix' },
      { group: 'Polaris', value: 'Polaris' },
      { group: 'Puffin', value: 'Puffin' },
      { group: 'QQBrowser', value: 'QQBrowser' },
      { group: 'Safari', value: 'Safari' },
      { group: 'Samsung Browser', value: 'Samsung Browser' },
      { group: 'SeaMonkey', value: 'SeaMonkey' },
      { group: 'Silk', value: 'Silk' },
      { group: 'Slim', value: 'Slim' },
      { group: 'UCBrowser', value: 'UCBrowser' },
      { group: 'Vivaldi', value: 'Vivaldi' },
      { group: 'WebKit', value: 'WebKit' },
      { group: 'Yandex', value: 'Yandex' }

    ],
    'Device language' : [
      { group: 'Abkhazian', value: 'AB' },
      { group: 'Afar', value: 'AA' },
      { group: 'Afrikaans', value: 'AF' },
      { group: 'Albanian', value: 'SQ' },
      { group: 'Amharic', value: 'AM' },
      { group: 'Arabic', value: 'AR' },
      { group: 'Aragonese', value: 'AN' },
      { group: 'Armenian', value: 'HY' },
      { group: 'Assamese', value: 'AS' },
      { group: 'Aymara', value: 'AY' },
      { group: 'Azerbaijani', value: 'AZ' },
      { group: 'Bashkir', value: 'BA' },
      { group: 'Basque', value: 'EU' },
      { group: 'Bengali (Bangla)', value: 'BN' },
      { group: 'Bhutani', value: 'DZ' },
      { group: 'Bihari', value: 'BH' },
      { group: 'Bislama', value: 'BI' },
      { group: 'Breton', value: 'BR' },
      { group: 'Bulgarian', value: 'BG' },
      { group: 'Burmese', value: 'MY' },
      { group: 'Byelorussian (Belarusian)', value: 'BE' },
      { group: 'Cambodian', value: 'KM' },
      { group: 'Catalan', value: 'CA' },
      { group: 'Chinese', value: 'ZH' },
      { group: 'Chinese (Simplified)', value: 'ZH-HANS' },
      { group: 'Chinese (Traditional)', value: 'ZH-HANT' },
      { group: 'Corsican', value: 'CO' },
      { group: 'Croatian', value: 'HR' },
      { group: 'Czech', value: 'CS' },
      { group: 'Danish', value: 'DA' },
      { group: 'Dutch', value: 'NL' },
      { group: 'English', value: 'EN' },
      { group: 'Esperanto', value: 'EO' },
      { group: 'Estonian', value: 'ET' },
      { group: 'Faeroese', value: 'FO' },
      { group: 'Farsi', value: 'FA' },
      { group: 'Fiji', value: 'FJ' },
      { group: 'Finnish', value: 'FI' },
      { group: 'French', value: 'FR' },
      { group: 'Frisian', value: 'FY' },
      { group: 'Galician', value: 'GL' },
      { group: 'Gaelic (Scottish)', value: 'GD' },
      { group: 'Gaelic (Manx)', value: 'GV' },
      { group: 'Georgian', value: 'KA' },
      { group: 'German', value: 'DE' },
      { group: 'Greek', value: 'EL' },
      { group: 'Greenlandic', value: 'KL' },
      { group: 'Guarani', value: 'GN' },
      { group: 'Gujarati', value: 'GU' },
      { group: 'Haitian Creole', value: 'HT' },
      { group: 'Hausa', value: 'HA' },
      { group: 'Hebrew', value: 'HE' },
      { group: 'Hebrew', value: 'IW' },
      { group: 'Hindi', value: 'HI' },
      { group: 'Hungarian', value: 'HU' },
      { group: 'Icelandic', value: 'IS' },
      { group: 'Ido', value: 'IO' },
      { group: 'Indonesian', value: 'ID' },
      { group: 'Indonesian', value: 'IN' },
      { group: 'Interlingua', value: 'IA' },
      { group: 'Interlingue', value: 'IE' },
      { group: 'Inuktitut', value: 'IU' },
      { group: 'Inupiak', value: 'IK' },
      { group: 'Irish', value: 'GA' },
      { group: 'Italian', value: 'IT' },
      { group: 'Japanese', value: 'JA' },
      { group: 'Javanese', value: 'JV' },
      { group: 'Kannada', value: 'KN' },
      { group: 'Kashmiri', value: 'KS' },
      { group: 'Kazakh', value: 'KK' },
      { group: 'Kinyarwanda (Ruanda)', value: 'RW' },
      { group: 'Kirghiz', value: 'KY' },
      { group: 'Kirundi (Rundi)', value: 'RN' },
      { group: 'Korean', value: 'KO' },
      { group: 'Kurdish', value: 'KU' },
      { group: 'Laothian', value: 'LO' },
      { group: 'Latin', value: 'LA' },
      { group: 'Latvian (Lettish)', value: 'LV' },
      { group: 'Limburgish ( Limburger)', value: 'LI' },
      { group: 'Lingala', value: 'LN' },
      { group: 'Lithuanian', value: 'LT' },
      { group: 'Macedonian', value: 'MK' },
      { group: 'Malagasy', value: 'MG' },
      { group: 'Malay', value: 'MS' },
      { group: 'Malayalam', value: 'ML' },
      { group: 'Maltese', value: 'MT' },
      { group: 'Maori', value: 'MI' },
      { group: 'Marathi', value: 'MR' },
      { group: 'Moldavian', value: 'MO' },
      { group: 'Mongolian', value: 'MN' },
      { group: 'Nauru', value: 'NA' },
      { group: 'Nepali', value: 'NE' },
      { group: 'Norwegian', value: 'NO' },
      { group: 'Occitan', value: 'OC' },
      { group: 'Oriya', value: 'OR' },
      { group: 'Oromo (Afaan Oromo)', value: 'OM' },
      { group: 'Pashto (Pushto)', value: 'PS' },
      { group: 'Polish', value: 'PL' },
      { group: 'Portuguese', value: 'PT' },
      { group: 'Punjabi', value: 'PA' },
      { group: 'Quechua', value: 'QU' },
      { group: 'Rhaeto-Romance', value: 'RM' },
      { group: 'Romanian', value: 'RO' },
      { group: 'Russian', value: 'RU' },
      { group: 'Samoan', value: 'SM' },
      { group: 'Sangro', value: 'SG' },
      { group: 'Sanskrit', value: 'SA' },
      { group: 'Serbian', value: 'SR' },
      { group: 'Serbo-Croatian', value: 'SH' },
      { group: 'Sesotho', value: 'ST' },
      { group: 'Setswana', value: 'TN' },
      { group: 'Shona', value: 'SN' },
      { group: 'Sichuan Yi', value: 'II' },
      { group: 'Sindhi', value: 'SD' },
      { group: 'Sinhalese', value: 'SI' },
      { group: 'Siswati', value: 'SS' },
      { group: 'Slovak', value: 'SK' },
      { group: 'Slovenian', value: 'SL' },
      { group: 'Somali', value: 'SO' },
      { group: 'Spanish', value: 'ES' },
      { group: 'Sundanese', value: 'SU' },
      { group: 'Swahili (Kiswahili)', value: 'SW' },
      { group: 'Swedish', value: 'SV' },
      { group: 'Tagalog', value: 'TL' },
      { group: 'Tajik', value: 'TG' },
      { group: 'Tamil', value: 'TA' },
      { group: 'Tatar', value: 'TT' },
      { group: 'Telugu', value: 'TE' },
      { group: 'Thai', value: 'TH' },
      { group: 'Tibetan', value: 'BO' },
      { group: 'Tigrinya', value: 'TI' },
      { group: 'Tonga', value: 'TO' },
      { group: 'Tsonga', value: 'TS' },
      { group: 'Turkish', value: 'TR' },
      { group: 'Turkmen', value: 'TK' },
      { group: 'Twi', value: 'TW' },
      { group: 'Uighur', value: 'UG' },
      { group: 'Ukrainian', value: 'UK' },
      { group: 'Urdu', value: 'UR' },
      { group: 'Uzbek', value: 'UZ' },
      { group: 'Vietnamese', value: 'VI' },
      { group: 'Volap?k', value: 'VO' },
      { group: 'Wallon', value: 'WA' },
      { group: 'Welsh', value: 'CY' },
      { group: 'Wolof', value: 'WO' },
      { group: 'Xhosa', value: 'XH' },
      { group: 'Yiddish', value: 'YI' },
      { group: 'Yiddish', value: 'JI' },
      { group: 'Yoruba', value: 'YO' },
      { group: 'Zulu', value: 'ZU' }
    ],
    Country: [
      { group: 'Afghanistan', value: 'AFG' },
      { group: 'Albania', value: 'ALB' },
      { group: 'Algeria', value: 'DZA' },
      { group: 'Andorra', value: 'AND' },
      { group: 'Angola', value: 'AGO' },
      { group: 'Antigua and Barbuda', value: 'ATG' },
      { group: 'Argentina', value: 'ARG' },
      { group: 'Armenia', value: 'ARM' },
      { group: 'Australia', value: 'AUS' },
      { group: 'Austria', value: 'AUT' },
      { group: 'Azerbaijan', value: 'AZE' },
      { group: 'The Bahamas', value: 'BHS' },
      { group: 'Bahrain', value: 'BHR' },
      { group: 'Bangladesh', value: 'BGD' },
      { group: 'Barbados', value: 'BRB' },
      { group: 'Belarus', value: 'BLR' },
      { group: 'Belgium', value: 'BEL' },
      { group: 'Belize', value: 'BLZ' },
      { group: 'Benin', value: 'BEN' },
      { group: 'Bhutan', value: 'BTN' },
      { group: 'Bolivia', value: 'BOL' },
      { group: 'Bosnia and Herzegovina', value: 'BIH' },
      { group: 'Botswana', value: 'BWA' },
      { group: 'Brazil', value: 'BRA' },
      { group: 'Brunei', value: 'BRN' },
      { group: 'Bulgaria', value: 'BGR' },
      { group: 'Burkina Faso', value: 'BFA' },
      { group: 'Burundi', value: 'BDI' },
      { group: 'Cambodia', value: 'KHM' },
      { group: 'Cameroon', value: 'CMR' },
      { group: 'Canada', value: 'CAN' },
      { group: 'Cape Verde', value: 'CPV' },
      { group: 'Central African Republic', value: 'CAF' },
      { group: 'Chad', value: 'TCD' },
      { group: 'Chile', value: 'CHL' },
      { group: 'China', value: 'CHN' },
      { group: 'Colombia', value: 'COL' },
      { group: 'Comoros', value: 'COM' },
      { group: 'Congo Republic of the', value: 'COG' },
      { group: 'Congo Democratic Republic of the', value: 'COD' },
      { group: 'Costa Rica', value: 'CRI' },
      { group: 'Cote d Ivoire', value: 'CIV' },
      { group: 'Croatia', value: 'HRV' },
      { group: 'Cuba', value: 'CUB' },
      { group: 'Cyprus', value: 'CYP' },
      { group: 'Czech Republic', value: 'CZE' },
      { group: 'Denmark', value: 'DNK' },
      { group: 'Djibouti', value: 'DJI' },
      { group: 'Dominica', value: 'DMA' },
      { group: 'Dominican Republic', value: 'DOM' },
      { group: 'East Timor (Timor-Leste)', value: 'TLS' },
      { group: 'Ecuador', value: 'ECU' },
      { group: 'Egypt', value: 'EGY' },
      { group: 'El Salvador', value: 'SLV' },
      { group: 'Equatorial Guinea', value: 'GNQ' },
      { group: 'Eritrea', value: 'ERI' },
      { group: 'Estonia', value: 'EST' },
      { group: 'Ethiopia', value: 'ETH' },
      { group: 'Fiji', value: 'FJI' },
      { group: 'Finland', value: 'FIN' },
      { group: 'France', value: 'FRA' },
      { group: 'Gabon', value: 'GAB' },
      { group: 'The Gambia', value: 'GMB' },
      { group: 'Georgia', value: 'GEO' },
      { group: 'Germany', value: 'DEU' },
      { group: 'Ghana', value: 'GHA' },
      { group: 'Greece', value: 'GRC' },
      { group: 'Grenada', value: 'GRD' },
      { group: 'Guatemala', value: 'GTM' },
      { group: 'Guinea', value: 'GIN' },
      { group: 'Guinea-Bissau', value: 'GNB' },
      { group: 'Guyana', value: 'GUY' },
      { group: 'Haiti', value: 'HTI' },
      { group: 'Honduras', value: 'HND' },
      { group: 'Hungary', value: 'HUN' },
      { group: 'Iceland', value: 'ISL' },
      { group: 'India', value: 'IND' },
      { group: 'Indonesia', value: 'IDN' },
      { group: 'Iran', value: 'IRN' },
      { group: 'Iraq', value: 'IRQ' },
      { group: 'Ireland', value: 'IRL' },
      { group: 'Israel', value: 'ISR' },
      { group: 'Italy', value: 'ITA' },
      { group: 'Jamaica', value: 'JAM' },
      { group: 'Japan', value: 'JPN' },
      { group: 'Jordan', value: 'JOR' },
      { group: 'Kazakhstan', value: 'KAZ' },
      { group: 'Kenya', value: 'KEN' },
      { group: 'Kiribati', value: 'KIR' },
      { group: 'Korea North', value: 'PRK' },
      { group: 'Korea South', value: 'KOR' },
      { group: 'Kosovo', value: 'XXK' },
      { group: 'Kuwait', value: 'KWT' },
      { group: 'Kyrgyzstan', value: 'KGZ' },
      { group: 'Laos', value: 'LAO' },
      { group: 'Latvia', value: 'LVA' },
      { group: 'Lebanon', value: 'LBN' },
      { group: 'Lesotho', value: 'LSO' },
      { group: 'Liberia', value: 'LBR' },
      { group: 'Libya', value: 'LBY' },
      { group: 'Liechtenstein', value: 'LIE' },
      { group: 'Lithuania', value: 'LTU' },
      { group: 'Luxembourg', value: 'LUX' },
      { group: 'Macedonia', value: 'MKD' },
      { group: 'Madagascar', value: 'MDG' },
      { group: 'Malawi', value: 'MWI' },
      { group: 'Malaysia', value: 'MYS' },
      { group: 'Maldives', value: 'MDV' },
      { group: 'Mali', value: 'MLI' },
      { group: 'Malta', value: 'MLT' },
      { group: 'Marshall Islands', value: 'MHL' },
      { group: 'Mauritania', value: 'MRT' },
      { group: 'Mauritius', value: 'MUS' },
      { group: 'Mexico', value: 'MEX' },
      { group: 'Micronesia Federated States of', value: 'FSM' },
      { group: 'Moldova', value: 'MDA' },
      { group: 'Monaco', value: 'MCO' },
      { group: 'Mongolia', value: 'MNG' },
      { group: 'Montenegro', value: 'MNE' },
      { group: 'Morocco', value: 'MAR' },
      { group: 'Mozambique', value: 'MOZ' },
      { group: 'Myanmar (Burma)', value: 'MMR' },
      { group: 'Namibia', value: 'NAM' },
      { group: 'Nauru', value: 'NRU' },
      { group: 'Nepal', value: 'NPL' },
      { group: 'Netherlands', value: 'NLD' },
      { group: 'New Zealand', value: 'NZL' },
      { group: 'Nicaragua', value: 'NIC' },
      { group: 'Niger', value: 'NER' },
      { group: 'Nigeria', value: 'NGA' },
      { group: 'Norway', value: 'NOR' },
      { group: 'Oman', value: 'OMN' },
      { group: 'Pakistan', value: 'PAK' },
      { group: 'Palau', value: 'PLW' },
      { group: 'Panama', value: 'PAN' },
      { group: 'Papua New Guinea', value: 'PNG' },
      { group: 'Paraguay', value: 'PRY' },
      { group: 'Peru', value: 'PER' },
      { group: 'Philippines', value: 'PHL' },
      { group: 'Poland', value: 'POL' },
      { group: 'Portugal', value: 'PRT' },
      { group: 'Qatar', value: 'QAT' },
      { group: 'Romania', value: 'ROU' },
      { group: 'Russia', value: 'RUS' },
      { group: 'Rwanda', value: 'RWA' },
      { group: 'Saint Kitts and Nevis', value: 'KNA' },
      { group: 'Saint Lucia', value: 'LCA' },
      { group: 'Saint Vincent and the Grenadines', value: 'VCT' },
      { group: 'Samoa', value: 'WSM' },
      { group: 'San Marino', value: 'SMR' },
      { group: 'Sao Tome and Principe', value: 'STP' },
      { group: 'Saudi Arabia', value: 'SAU' },
      { group: 'Senegal', value: 'SEN' },
      { group: 'Serbia', value: 'SRB' },
      { group: 'Seychelles', value: 'SYC' },
      { group: 'Sierra Leone', value: 'SLE' },
      { group: 'Singapore', value: 'SGP' },
      { group: 'Slovakia', value: 'SVK' },
      { group: 'Slovenia', value: 'SVN' },
      { group: 'Solomon Islands', value: 'SLB' },
      { group: 'Somalia', value: 'SOM' },
      { group: 'South Africa', value: 'ZAF' },
      { group: 'South Sudan', value: 'SSD' },
      { group: 'Spain', value: 'ESP' },
      { group: 'Sri Lanka', value: 'LKA' },
      { group: 'Sudan', value: 'SDN' },
      { group: 'Suriname', value: 'SUR' },
      { group: 'Swaziland', value: 'SWZ' },
      { group: 'Sweden', value: 'SWE' },
      { group: 'Switzerland', value: 'CHE' },
      { group: 'Syria', value: 'SYR' },
      { group: 'Taiwan', value: 'TWN' },
      { group: 'Tajikistan', value: 'TJK' },
      { group: 'Tanzania', value: 'TZA' },
      { group: 'Thailand', value: 'THA' },
      { group: 'Togo', value: 'TGO' },
      { group: 'Tonga', value: 'TON' },
      { group: 'Trinidad and Tobago', value: 'TTO' },
      { group: 'Tunisia', value: 'TUN' },
      { group: 'Turkey', value: 'TUR' },
      { group: 'Turkmenistan', value: 'TKM' },
      { group: 'Tuvalu', value: 'TUV' },
      { group: 'Uganda', value: 'UGA' },
      { group: 'Ukraine', value: 'UKR' },
      { group: 'United Arab Emirates', value: 'ARE' },
      { group: 'United Kingdom', value: 'GBR' },
      { group: 'United States of America', value: 'USA' },
      { group: 'Uruguay', value: 'URY' },
      { group: 'Uzbekistan', value: 'UZB' },
      { group: 'Vanuatu', value: 'VUT' },
      { group: 'Vatican City (Holy See)', value: 'VAT' },
      { group: 'Venezuela', value: 'VEN' },
      { group: 'Vietnam', value: 'VNM' },
      { group: 'Yemen', value: 'YEM' },
      { group: 'Zambia', value: 'ZMB' },
      { group: 'Zimbabwe', value: 'ZWE' },
      { group: 'Hong Kong', value: 'HKG' },
      { group: 'Puerto-Rico', value: 'PRI' },
      { group: 'American Samoa', value: 'ASM' },
      { group: 'Anguilla', value: 'AIA' },
      { group: 'Antarctica', value: 'ATA' },
      { group: 'Aruba', value: 'ABW' },
      { group: 'Bermuda', value: 'BMU' },
      { group: 'British Indian Ocean Territory', value: 'IOT' },
      { group: 'British Virgin Islands', value: 'VGB' },
      { group: 'Cayman Islands', value: 'CYM' },
      { group: 'Christmas Island', value: 'CXR' },
      { group: 'Cocos Islands', value: 'CCK' },
      { group: 'Cook Islands', value: 'COK' },
      { group: 'Curacao', value: 'CUW' },
      { group: 'Falkland Islands', value: 'FLK' },
      { group: 'Faroe Islands', value: 'FRO' },
      { group: 'French Polynesia', value: 'PYF' },
      { group: 'Gibraltar', value: 'GIB' },
      { group: 'Greenland', value: 'GRL' },
      { group: 'Guam', value: 'GUM' },
      { group: 'Guernsey', value: 'GGY' },
      { group: 'Isle of Man', value: 'IMN' },
      { group: 'Jersey', value: 'JEY' },
      { group: 'Macau', value: 'MAC' },
      { group: 'Mayotte', value: 'MYT' },
      { group: 'Montserrat', value: 'MSR' },
      { group: 'Netherlands Antilles', value: 'ANT' },
      { group: 'New Caledonia', value: 'NCL' },
      { group: 'Niue', value: 'NIU' },
      { group: 'Northern Mariana Islands', value: 'MNP' },
      { group: 'Palestine', value: 'PSE' },
      { group: 'Pitcairn', value: 'PCN' },
      { group: 'Reunion', value: 'REU' },
      { group: 'Saint Barthelemy', value: 'BLM' },
      { group: 'Saint Helena', value: 'SHN' },
      { group: 'Saint Martin', value: 'MAF' },
      { group: 'Saint Pierre and Miquelon', value: 'SPM' },
      { group: 'Sint Maarten', value: 'SXM' },
      { group: 'Svalbard and Jan Mayen', value: 'SJM' },
      { group: 'Tokelau', value: 'TKL' },
      { group: 'Turks and Caicos Islands', value: 'TCA' },
      { group: 'U.S. Virgin Islands', value: 'VIR' },
      { group: 'Wallis and Futuna', value: 'WLF' },
      { group: 'Western Sahara', value: 'ESH' }
    ],
    City: [
      { group: 'Kiev', value: 'UKR', name: 'Arts & Entertainment'},
      { group: 'Moscow', value: 'RUS', name: 'Arts & Entertainment'},
      { group: 'Washington', value: 'USA', name: 'Arts & Entertainment'},
    ],
    userGender: [
      { group: 'Male', value: 'M'},
      { group: 'Female', value: 'F'},
      { group: 'Other', value: 'O'},
      { group: 'Unknown', value: 'U'},
    ],
    geoRegions: [  { group: 'Alabama', value: 'AL' },
      { group: 'Alaska', value: 'AK' },
      { group: 'Arizona', value: 'AZ' },
      { group: 'Arkansas', value: 'AR' },
      { group: 'California', value: 'CA' },
      { group: 'Colorado', value: 'CO' },
      { group: 'Connecticut', value: 'CT' },
      { group: 'Delaware', value: 'DE' },
      { group: 'District Of Columbia', value: 'DC' },
      { group: 'Florida', value: 'FL' },
      { group: 'Georgia', value: 'GA' },
      { group: 'Hawaii', value: 'HI' },
      { group: 'Idaho', value: 'ID' },
      { group: 'Illinois', value: 'IL' },
      { group: 'Indiana', value: 'IN' },
      { group: 'Iowa', value: 'IA' },
      { group: 'Kansas', value: 'KS' },
      { group: 'Kentucky', value: 'KY' },
      { group: 'Louisiana', value: 'LA' },
      { group: 'Maine', value: 'ME' },
      { group: 'Maryland', value: 'MD' },
      { group: 'Massachusetts', value: 'MA' },
      { group: 'Michigan', value: 'MI' },
      { group: 'Minnesota', value: 'MN' },
      { group: 'Mississippi', value: 'MS' },
      { group: 'Missouri', value: 'MO' },
      { group: 'Montana', value: 'MT' },
      { group: 'Nebraska', value: 'NE' },
      { group: 'Nevada', value: 'NV' },
      { group: 'New Hampshire', value: 'NH' },
      { group: 'New Jersey', value: 'NJ' },
      { group: 'New Mexico', value: 'NM' },
      { group: 'New York', value: 'NY' },
      { group: 'North Carolina', value: 'NC' },
      { group: 'North Dakota', value: 'ND' },
      { group: 'Ohio', value: 'OH' },
      { group: 'Oklahoma', value: 'OK' },
      { group: 'Oregon', value: 'OR' },
      { group: 'Pennsylvania', value: 'PA' },
      { group: 'Rhode Island', value: 'RI' },
      { group: 'South Carolina', value: 'SC' },
      { group: 'South Dakota', value: 'SD' },
      { group: 'Tennessee', value: 'TN' },
      { group: 'Texas', value: 'TX' },
      { group: 'Utah', value: 'UT' },
      { group: 'Vermont', value: 'VT' },
      { group: 'Virginia', value: 'VA' },
      { group: 'Washington', value: 'WA' },
      { group: 'West Virginia', value: 'WV' },
      { group: 'Wisconsin', value: 'WI' },
      { group: 'Wyoming', value: 'WY' }
    ],
    Regions : [  { group: 'Andaman and Nicobar Islands', value : 'AN' },
      { group: 'Andhra Pradesh', value : 'AP' },
      { group: 'Arunachal Pradesh', value : 'AR' },
      { group: 'Assam', value : 'AS' },
      { group: 'Bihar', value : 'BR' },
      { group: 'Chandigarh', value : 'CH' },
      { group: 'Chhattisgarh', value : 'CT' },
      { group: 'Dadra and Nagar Haveli and Daman and Diu', value : 'DH' },
      { group: 'Delhi', value : 'DL' },
      { group: 'Goa', value : 'GA' },
      { group: 'Gujarat', value : 'GJ' },
      { group: 'Haryana', value : 'HR' },
      { group: 'Himachal Pradesh', value : 'HP' },
      { group: 'Jammu and Kashmir', value : 'JK' },
      { group: 'Jharkhand', value : 'JH' },
      { group: 'Karnataka', value : 'KA' },
      { group: 'Kerala', value : 'KL' },
      { group: 'Ladakh', value : 'LA' },
      { group: 'Lakshadweep', value : 'LD' },
      { group: 'Madhya Pradesh', value : 'MP' },
      { group: 'Maharashtra', value : 'MH' },
      { group: 'Manipur', value : 'MN' },
      { group: 'Meghalaya', value : 'ML' },
      { group: 'Mizoram', value : 'MZ' },
      { group: 'Nagaland', value : 'NL' },
      { group: 'Odisha', value : 'OR' },
      { group: 'Puducherry', value : 'PY' },
      { group: 'Punjab', value : 'PB' },
      { group: 'Rajasthan', value : 'RJ' },
      { group: 'Sikkim', value : 'SK' },
      { group: 'Tamil Nadu', value : 'TN' },
      { group :'Telangana', value : 'TG' },
      { group: 'Tripura', value : 'TR' },
      { group: 'Uttarakhand', value : 'UT' },
      { group: 'Uttar Pradesh', value : 'UP' },
      { group: 'West Bengal', value : 'WB' }
    ]
  };
  categoriesList = [
    { group: 'IAB1 Arts & Entertainment', value: 'IAB1'},
    { group: 'IAB2 Automotive', value: 'IAB2'},
    { group: 'IAB3 Business', value: 'IAB3'},
    { group: 'IAB4 Careers', value: 'IAB4'},
    { group: 'IAB5 Education', value: 'IAB5'},
    { group: 'IAB6 Family & Parenting', value: 'IAB6'},
    { group: 'IAB7 Health & Fitness', value: 'IAB7'},
    { group: 'IAB8 Food & Drink', value: 'IAB8'},
    { group: 'IAB9 Hobbies & Interests', value: 'IAB9'},
    { group: 'IAB10 Home & Garden', value: 'IAB10'},
    { group: 'IAB11 Law, Gov\'t & Politics', value: 'IAB11'},
    { group: 'IAB12 News', value: 'IAB12'},
    { group: 'IAB13 Personal Finance', value: 'IAB13'},
    { group: 'IAB14 Society', value: 'IAB14'},
    { group: 'IAB15 Science', value: 'IAB15'},
    { group: 'IAB16 Pets', value: 'IAB16'},
    { group: 'IAB17 Sports', value: 'IAB17'},
    { group: 'IAB18 Style & Fashion', value: 'IAB18'},
    { group: 'IAB19 Technology & Computing', value: 'IAB19'},
    { group: 'IAB20 Travel', value: 'IAB20'},
    { group: 'IAB21 Real Estate', value: 'IAB21'},
    { group: 'IAB22 Shopping', value: 'IAB22'},
    { group: 'IAB23 Religion & Spirituality', value: 'IAB23'}
  ];
  paymentMethods = [
    { group: 'Account Balance', value: 0},
    { group: 'PayPal', value: 1},
    { group: 'Credit Card', value: 2},
    { group: 'Manual CashIn(old)', value: 3},
    { group: 'ePayments', value: 4},
    { group: 'wire transfer', value: 5},
    { group: 'Balticums', value: 6},
    { group: 'Pasta', value: 7},
    { group: 'Bank of America', value: 8},
  ]
    constructor() {}
    getPaymentMethods(){
    return this.paymentMethods
    }
    getTimeTargetingList(){
      return this.timeTargetingEnableApplySelect;
    }
    getTimeZoneOptions(){
      return this.timezone_options;
    }
    getCommonTargetingList(){
      return this.commonTargetingList;
    }
    getCategoriesList(){
      return this.categoriesList;
    }
    getVideoAudioAdm(adType='video', duration='00:00:01', mediaFile, bitrate, clickUrl){
          return `<VAST version="4.1">
                        <Ad id="20007" sequence="1" conditionalAd="false" adType="${adType}">
        <InLine>
          <AdSystem version="4.1">DecenterAds</AdSystem>
          <AdServingId>required-a532d16d-4d7f-4440-bd29-2ec0e693fc81</AdServingId>
          <AdTitle>DecenterAds audio ad</AdTitle>
          <Creatives>
            <Creative >
              <UniversalAdId >unknown</UniversalAdId>
              <Linear>
                <Duration>${duration}</Duration>
                <MediaFiles>
                  <MediaFile id="5241" delivery="progressive" type="video/mp4" bitrate="${bitrate}">
                    <![CDATA[${mediaFile}]]>
                  </MediaFile>
                  <MediaFile id="5244" delivery="progressive" type="video/mp4" bitrate="${bitrate}" >
                    <![CDATA[${mediaFile}]]>
                  </MediaFile>
                  <MediaFile id="5246" delivery="progressive" type="video/mp4" bitrate="${bitrate}">
                    <![CDATA[${mediaFile}]]>
                  </MediaFile>
                </MediaFiles>
                <VideoClicks>
                  <ClickThrough>
                    <![CDATA[${clickUrl}]]>
                  </ClickThrough>
                </VideoClicks>
              </Linear>
            </Creative>
          </Creatives>
        </InLine>
      </Ad>
                  </VAST>`;
    }
  prepareAdmBody(creativeType, src, duration = '', bitrate=0, clickUrl = '' ) {
    let result = '';
    let admBodyStatic = '';
    // let creativeType = ;
    if (creativeType === 'banner') {
      src = `img src="${src}"`;
      admBodyStatic = `<a href="${clickUrl}" target="_blank"><img src="" alt=""></a>`;
      result = admBodyStatic.replace('img src=""', src);
    } else if (creativeType === 'video'
        || creativeType === 'audio') {
      result = this.getVideoAudioAdm(creativeType, duration, src, bitrate, clickUrl);
    }
    else if (creativeType === 'native') {
      result = 'null'
    }
    return result;
  }
  getChartColors (){
      return [
        "#8fe22a", "#ef6e3c", "#4680ff", "#dd93fd",
        "#3f8473", "#b11573", "#250662", "#cb5bea",
        "#228916", "#ac3e1b", "#c9a941", "#41d158",
        "#6749e8", "#0971f0", "#8fb413", "#b2b4f0",
      "#f205e6" ,"#1c0365" ,"#14a9ad" ,"#4ca2f9",
        "#d298e2" ,"#6119d0",
      "#9348af" ,"#01ac53" ,"#c5a4fb" ,"#996635",
        "#d2737d" ,"#c0a43c" ,"#f2510e" ,"#651be6" ,
        "#79806e" ,"#61da5e" ,"#cd2f00" ,
        "#63b598", "#ce7d78", "#ea9e70", "#a48a9e", "#c6e1e8", "#648177" ,"#0d5ac1",
      "#2f3f94" ,"#2f7b99" ,"#da967d" ,"#34891f" ,"#b0d87b" ,"#ca4751" ,"#7e50a8" ,
      "#c4d647" ,"#e0eeb8" ,"#11dec1" ,"#289812" ,"#566ca0" ,"#ffdbe1" ,"#2f1179" ,
      "#935b6d" ,"#916988" ,"#513d98" ,"#aead3a", "#9e6d71", "#4b5bdc", "#0cd36d",

        "#df514a", "#539397", "#880977",
      "#f697c1", "#ba96ce", "#679c9d", "#c6c42c", "#5d2c52", "#48b41b", "#e1cf3b",
      "#5be4f0", "#57c4d8", "#a4d17a", "#be608b", "#96b00c", "#088baf",
      "#f158bf", "#e145ba", "#ee91e3", "#05d371", "#5426e0", "#4834d0", "#802234",
      "#fb21a3", "#51aed9", "#5bb32d", "#21538e", "#89d534", "#d36647",
      "#7fb411", "#0023b8", "#3b8c2a", "#986b53", "#f50422", "#983f7a", "#ea24a3",
      "#79352c", "#521250", "#c79ed2", "#d6dd92", "#e33e52", "#b2be57", "#fa06ec",
      "#1bb699", "#6b2e5f", "#64820f", "#21538e", "#89d534", "#d36647",
      "#7fb411", "#0023b8", "#3b8c2a", "#986b53", "#f50422", "#983f7a", "#ea24a3",
      "#79352c", "#521250", "#c79ed2", "#d6dd92", "#e33e52", "#b2be57", "#fa06ec",
      "#1bb699", "#6b2e5f", "#64820f", "#9cb64a", "#996c48", "#9ab9b7",
      "#06e052", "#e3a481", "#0eb621", "#fc458e", "#b2db15", "#aa226d", "#792ed8",
      "#73872a", "#520d3a", "#cefcb8", "#a5b3d9", "#7d1d85", "#c4fd57", "#f1ae16",
      "#421f79", "#7a3d93", "#635f6d", "#93f2d7", "#9b5c2a", "#15b9ee", "#0f5997",
      "#409188", "#911e20", "#1350ce", "#10e5b1", "#fff4d7", "#cb2582", "#ce00be",
      "#32d5d6", "#17232", "#608572", "#c79bc2", "#00f87c", "#77772a", "#6995ba",
      "#fc6b57", "#f07815", "#8fd883", "#060e27", "#96e591", "#21d52e", "#d00043",
      "#b47162", "#1ec227", "#4f0f6f", "#1d1d58", "#947002", "#bde052", "#e08c56",
      "#28fcfd", "#bb09b", "#36486a", "#d02e29", "#1ae6db", "#3e464c", "#a84a8f",
      "#911e7e", "#3f16d9", "#0f525f", "#ac7c0a", "#b4c086", "#c9d730", "#30cc49",
      "#3d6751", "#fb4c03", "#640fc1", "#62c03e", "#d3493a", "#88aa0b", "#406df9",
      "#615af0", "#4be47", "#2a3434", "#4a543f", "#79bca0", "#a8b8d4", "#00efd4",
      "#7ad236", "#7260d8", "#1deaa7", "#06f43a", "#823c59", "#e3d94c", "#dc1c06",
      "#f53b2a", "#b46238", "#2dfff6", "#a82b89", "#1a8011", "#436a9f", "#1a806a",
      "#4cf09d", "#c188a2", "#67eb4b", "#b308d3", "#fc7e41", "#af3101", "#ff065",
      "#71b1f4", "#a2f8a5", "#e23dd0", "#d3486d", "#00f7f9", "#474893", "#3cec35",
      "#1c65cb", "#5d1d0c", "#2d7d2a", "#ff3420", "#5cdd87", "#a259a4", "#e4ac44",
      "#1bede6", "#8798a4", "#d7790f", "#b2c24f", "#de73c2", "#d70a9c", "#25b67",
      "#88e9b8", "#c2b0e2", "#86e98f", "#ae90e2", "#1a806b", "#436a9e", "#0ec0ff",
      "#f812b3", "#b17fc9", "#8d6c2f", "#d3277a", "#2ca1ae", "#9685eb", "#8a96c6",
      "#dba2e6", "#76fc1b", "#608fa4", "#20f6ba", "#07d7f6", "#dce77a", "#77ecca"]
  }
}

